name: LiqhtLab
version: '${project.version}'
main: net.liqht.liqhtlab.LiqhtLab
api-version: 1.19
authors: [ Liqht_ ]
commands:
  rizzwand:
    description: gives an admin a wand that can kill any player by looking at them
